networks:
    printer-monitor-net:

services:
    obico-ml-api:
        image: ghcr.io/gabe565/obico/ml-api
        container_name: printer-monitor-obico-ml-api
        hostname: obico-ml-api
        environment:
            DEBUG: "True"
            FLASK_APP: "server.py"
            # ML_API_TOKEN:
        restart: unless-stopped
        tty: true
        networks:
            - printer-monitor-net
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "wget --no-verbose --tries=1 --spider http://localhost:3333/hc/",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
        command:
            [
                gunicorn,
                --bind=0.0.0.0:3333,
                --workers=1,
                --access-logfile=-,
                wsgi,
            ]

    printer-monitor:
        image: ghcr.io/xorza/printer-monitor:main
        container_name: printer-monitor
        hostname: printer-monitor
        env_file: .env
        environment:
            OBICO_URL: http://obico-ml-api:3333
            OBICO_IMAGE_HOST: printer-monitor:8099
        volumes:
            - ./volume/data:/data
        restart: unless-stopped
        networks:
            - printer-monitor-net
        depends_on:
            obico-ml-api:
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8099/health"]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 10s
